name: NWChem-wiki.mirroring

on: [push, pull_request]

jobs:
  wiki_mirroring:
    runs-on: [ubuntu-latest]  
    steps: 
      - name: Checkout nwchem-wiki
        uses: actions/checkout@v2
        with:
          repository: edoapra/nwchem-wiki    
      - name: fetch and merge
        run: |
          env|egrep GITHU
          git config user.name "edoapra"
          git config user.email "edoardo.apra@gmail.com"
          git remote remove origin
          git remote add origin https://$GITHUB_API_KEY@github.com/edoapra/nwchem-wiki.git > /dev/null 2>&1
          git remote add upstream https://$GITHUB_API_KEY@github.com/edoapra/nwchem.wiki.git > /dev/null 2>&1
          git remote -v
          git fetch origin
          git fetch upstream
          git merge upstream/master --no-edit
          git push origin HEAD:master > /dev/null 2>&1
          git push upstream HEAD:master > /dev/null 2>&1
